name: Build and publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests with Gradle
        run: ./gradlew :shader-foundry:build

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: | 
            ./shader-foundry/build/outputs/aar/shader-foundry-debug.aar
            ./shader-foundry/build/outputs/aar/shader-foundry-release.aar
