name: Build and publish

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: ‘corretto’
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests with Gradle
        run: ./gradlew :EasyShaders

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: | 
            ./EasyShaders/build/outputs/aar/EasyShaders-debug.aar
            ./EasyShaders/build/outputs/aar/EasyShaders-release.aar
